spring:
  config:
    import: "optional:configserver:http://rtr-config-server:8888"
    activate:
      on-profile: docker
  rabbitmq:
    host: rtr-rabbitmq
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://kcs-keycloak:8080/realms/rtr-ms
eureka:
  client:
    service-url:
      defaultZone: http://rtr-eureka-server:8761/eureka/