app:
  base-url: http://localhost:${server.port}
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
server:
  port: 8000
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: qwer
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
  application:
    name: report-app-bff
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rtr-ms
        registration:
          nextjs:
            provider: keycloak
            client-id: nextjs
            client-secret: nSWtrvNvBZH6jfLBj42IWSG31TiuSBUi
            redirect-uri: http://localhost:8000/login/oauth2/code/nextjs
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin@123
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
            - SaveSession
            - TokenRelay=
          routes:
            - id: customer
              #uri: http://localhost:16800
              uri: lb://customer
              predicates:
                - Path=/customer-service/**
              filters:
                - RewritePath=/customer-service/(?<segment>.*),/$\{segment}
            - id: account
              #uri: http://localhost:16800
              uri: lb://account
              predicates:
                - Path=/account-service/**
              filters:
              - RewritePath=/account-service/(?<segment>.*),/$\{segment}
              - name: CircuitBreaker
                args:
                  name: accountCircuitBreaker
                  fallbackUri: forward:/fallback/account-service/api/v1/accounts
            - id: nextjs
              uri: http://localhost:3000
              predicates:
                - Path=/**
  rabbitmq:
    host: localhost
    username: admin
    password: password
    port: 5672
management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    configs:
      default:
        # monitoring 10 requests before transition CLOSE into OPEN state
        slidingWindowSize: 10
        # This parameter defines that only 2 calls are permitted in the HALF_OPEN state.
        # If these calls succeed, the CircuitBreaker may transition back to CLOSED; if they fail, it will return to OPEN
        permittedNumberOfCallsInHalfOpenState: 2
        # 50% of requests are failed, it will move into OPEN state
        failureRateThreshold: 50
        # wait 10 seconds in the OPEN state before attempting to test the downstream service again.
        waitDurationInOpenState: 10000

logging:
  level:
    kh:
      edu:
        cstad:
          reportappbff: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
